depromeet/teum-teum-server

- .github/workflows/integration-tester.yml
- .github/workflows/type-labeler.yml
integration-tester 가 develop 브랜치 대상으로도 수행되도록 수정
type-labeler에 오타 수정
- close #9
> ci: type-labeler, integration-tester 수정

- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
- src/main/java/net/teumteum/user/service/UserService.java
- src/test/java/net/teumteum/user/domain/UserFixture.java
- src/test/java/net/teumteum/user/integration/Api.java
- src/test/java/net/teumteum/user/integration/IntegrationTest.java
- src/test/java/net/teumteum/user/integration/Repository.java
- src/test/java/net/teumteum/user/integration/UserIntegrationTest.java
- src/test/java/net/teumteum/user/service/UserConnectorTest.java
유저 id들로 유저들을 조회하는 API를 개발했습니다.
- close #14
> feat: 유저 id들로 유저 조회 API 개발

- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/java/net/teumteum/user/domain/User.java
- src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
- src/main/java/net/teumteum/user/service/UserService.java
- src/test/java/net/teumteum/user/integration/Api.java
- src/test/java/net/teumteum/user/integration/RequestFixture.java
- src/test/java/net/teumteum/user/integration/UserIntegrationTest.java
유저 정보 업데이트 기능을 추가했습니다.
- close #17
> feat: 유저 업데이트 기능 추가

- build.gradle
- gradle.properties
- gradle/apm.gradle
- settings.gradle
- src/main/java/net/teumteum/core/advice/GlobalExceptionHandler.java
- src/main/java/net/teumteum/meeting/controller/MeetingController.java
- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/resources/application-prod.yml
Sentry를 연동했습니다.
- close #22 
[sentry 팀 페이지](https://teum-teum.sentry.io/projects/java-spring-boot/?project=4506545307320320)
> feat: Sentry 연동

- gradle/devtool.gradle
- gradle/spring.gradle
- src/main/java/net/teumteum/core/security/Authenticated.java
- src/main/java/net/teumteum/core/security/SecurityConfig.java
- src/main/java/net/teumteum/core/security/UserAuthentication.java
- src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
- src/main/resources/application-auth.yml
- src/main/resources/application-datasource.yml
- src/main/resources/application-dev.yml
- src/main/resources/db/migration/V4__update_users.sql
기존 인증 관련 코드 리팩토링 및 추가 구현을 진행했으며, 소셜 로그인 관련 설정 추가
- close #31
> feat: 인증 로직 리팩토링 및 추가 구현, 카카오,네이버 소셜 로그인 관련 설정 추가

- src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
- src/main/java/net/teumteum/auth/domain/CustomOAuthUser.java
- src/main/java/net/teumteum/auth/domain/KakaoOAuthUserInfo.java
- src/main/java/net/teumteum/auth/domain/NaverOAuthUserInfo.java
- src/main/java/net/teumteum/auth/domain/OAuthToken.java
- src/main/java/net/teumteum/auth/domain/OAuthUserAttributes.java
- src/main/java/net/teumteum/auth/domain/OAuthUserInfo.java
- src/main/java/net/teumteum/auth/domain/response/TokenResponse.java
- src/main/java/net/teumteum/auth/service/AuthService.java
- src/main/java/net/teumteum/auth/service/OAuthService.java
- src/main/java/net/teumteum/core/security/SecurityConfig.java
- src/main/java/net/teumteum/core/security/config/CorsConfig.java
- src/main/java/net/teumteum/core/security/filter/JwtAccessDeniedHandler.java
- src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
- src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
- src/main/java/net/teumteum/core/security/service/JwtService.java
- src/main/java/net/teumteum/core/security/service/RedisService.java
- src/main/java/net/teumteum/core/security/service/SecurityService.java
- src/main/java/net/teumteum/user/infra/WebClientConfigurer.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/resources/application.properties
- webclient 통신 방식으로 소셜 로그인을 구현했으며 관련 에러를 수정했습니다.
- close #43
> refactor: 소셜 로그인 관련 에러 수정 및 exception handler 추가

- src/main/java/net/teumteum/auth/service/OAuthService.java
- src/main/java/net/teumteum/core/config/RedisConfig.java
- src/main/java/net/teumteum/core/security/service/JwtService.java
- src/main/java/net/teumteum/core/security/service/RedisService.java
- src/test/resources/application.properties
- Redis 관련 설정 클래스 구현 및 기타 코드 리팩토링
- close #49 
[Redis Configuration - Lettuce VS Jedis & RedisTemplate](https://akku-dev.tistory.com/105)
> feat: Redis 관련 설정 클래스를 구현하고 적용한다.

- src/main/resources/application-aws.yml
- src/main/resources/application-prod.yml
MySQL Dialect를 설정했습니다.
- close #63
> build: MySQL Dialect 설정

- Dockerfile
Dockerfile의 datasource가 중복되는 버그를 수정했습니다.
- close #66
> build: Dockerfile datasource 중복 버그 수정

- src/main/resources/db/migration/V1__create_users.sql
- src/test/resources/schema.sql
> release: 0.0.6

- src/main/resources/db/migration/V4__update_users.sql
- src/test/resources/schema.sql
> release: 0.0.7

- src/main/java/net/teumteum/auth/service/OAuthService.java
- src/main/java/net/teumteum/user/controller/UserController.java
- src/test/java/net/teumteum/core/security/SecurityServiceTest.java
- src/test/java/net/teumteum/integration/Api.java
- src/test/java/net/teumteum/integration/IntegrationTest.java
- src/test/java/net/teumteum/integration/Repository.java
- 기존 API 을 Restful 하게 수정하고 누락된 테스트 코드를 작성합니다.
- close #81
> refactor: 기존 API & 코드 리팩토링 및 누락된 테스트 코드 구현

- gradle.properties
- gradle/devtool.gradle
- gradle/test.gradle
- src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
- src/main/java/net/teumteum/auth/service/OAuthService.java
- src/main/java/net/teumteum/core/error/ErrorResponse.java
- src/main/java/net/teumteum/core/security/SecurityConfig.java
- src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
- src/main/java/net/teumteum/core/security/service/SecurityService.java
- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/java/net/teumteum/user/service/UserService.java
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/test/java/net/teumteum/core/config/RedisTestContainerConfig.java
- src/test/java/net/teumteum/core/security/SecurityServiceTest.java
- src/test/java/net/teumteum/integration/Api.java
- src/test/java/net/teumteum/integration/IntegrationTest.java
- src/test/java/net/teumteum/integration/Repository.java
- src/test/java/net/teumteum/integration/UserIntegrationTest.java
> release: 0.0.8

- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
- src/main/java/net/teumteum/user/service/UserService.java
- src/test/java/net/teumteum/integration/UserIntegrationTest.java
> feat: 내 정보 조회 API 구현

- src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
GPT api 엔드포인트를 설정했습니다.
- close #92
> fix: GPT api uri가 세팅되어있지 않은 버그 수정

- src/main/resources/db/migration/V6__create_users_interests.sql
기존 V5__update_users.sql 오류 수정 및 V6__create_users_interests.sql 추가
- close #109
> fix: flyway 오류 수정

- build.gradle
- gradle.properties
- gradle/gatling.gradle
- src/gatling/java/protocol/Protocol.java
- src/gatling/java/simulation/GetUserSimulation.java
- src/gatling/java/simulation/SimulationSample.java
- src/gatling/resources/gatling.conf
- src/gatling/resources/recorder.conf
부하테스트 툴 Gatling 을 세팅했습니다.
- close #21
> build: Gatling 세팅

- src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
- src/test/java/net/teumteum/integration/Api.java
- src/test/java/net/teumteum/integration/UserIntegrationTest.java
내 정보 조회에 Oauth 정보 추가
close #118
> feat: 내 정보 조회에 Oauth 정보 추가

- src/main/java/net/teumteum/auth/service/AuthService.java
- src/main/java/net/teumteum/core/security/SecurityConfig.java
- src/main/java/net/teumteum/core/security/service/JwtService.java
- src/main/java/net/teumteum/core/security/service/RedisService.java
- src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
안드로이드 연동 과정에서 발생한 JWT 재발급 에러 수정
- clase #132
> fix: JWT 재발급 오류 해결

- src/main/java/net/teumteum/core/security/service/JwtService.java
Sentry 에 찍힌 JWT 파싱 에러 수정
- close #142
> fix: JWT 파싱 관련 에러 수정

- src/main/java/net/teumteum/meeting/domain/MeetingConnector.java
- src/main/java/net/teumteum/meeting/domain/MeetingRepository.java
- src/main/java/net/teumteum/meeting/service/MeetingConnectorImpl.java
- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/java/net/teumteum/user/domain/Review.java
- src/main/java/net/teumteum/user/domain/User.java
- src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
- src/main/java/net/teumteum/user/domain/request/UserRegisterRequest.java
- src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
- src/main/java/net/teumteum/user/service/UserService.java
- src/main/resources/db/migration/V9__create_users_reviews.sql
- src/test/java/net/teumteum/integration/Api.java
- src/test/java/net/teumteum/integration/Repository.java
- src/test/java/net/teumteum/integration/RequestFixture.java
- src/test/java/net/teumteum/integration/UserIntegrationTest.java
- src/test/java/net/teumteum/meeting/service/MeetingConnectorTest.java
- src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
- src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
- src/test/java/net/teumteum/user/domain/UserFixture.java
- src/test/resources/schema.sql
회원 리뷰 등록 기능을 구현했습니다.
- close #140 
- 기존 노션에 적혀있었던 API 을 조금 수정했습니다 ❗️ 
-   기존 유저의 리뷰 데이터를 하나씩 보내는 방식에서 한번에 다 보내는 방식으로 변경 🙋
> feat: 회원 리뷰 등록 기능 구현

- src/main/java/net/teumteum/meeting/controller/MeetingController.java
- src/main/java/net/teumteum/meeting/service/MeetingService.java
특정 모임에 대한 신고 기능 구현
특정 모임에 대한 신고 기능 구현
close #154
> feat: 모임 신고 기능 구현

- src/main/java/net/teumteum/meeting/controller/MeetingController.java
- src/main/java/net/teumteum/meeting/domain/Meeting.java
- src/main/java/net/teumteum/meeting/domain/request/UpdateMeetingRequest.java
- src/main/java/net/teumteum/meeting/service/MeetingService.java
- src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
> feat: 모임 수정 기능 추가

- src/main/java/net/teumteum/user/controller/UserController.java
- src/main/java/net/teumteum/user/domain/Review.java
- src/main/java/net/teumteum/user/domain/User.java
- src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
- src/main/java/net/teumteum/user/service/UserService.java
- src/test/java/net/teumteum/integration/Api.java
- src/test/java/net/teumteum/integration/Repository.java
- src/test/java/net/teumteum/integration/RequestFixture.java
- src/test/java/net/teumteum/integration/UserIntegrationTest.java
- src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
- src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
- src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
- src/test/java/net/teumteum/user/domain/UserFixture.java
> release: 0.2.5

- src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
GPT 버전을 3.5에서 4로 업그레이드 했습니다. 
- close #173
> perf: upgrade GPT-3.5 to GPT-4

- src/main/java/net/teumteum/alert/app/AlertHandler.java
- src/main/java/net/teumteum/alert/domain/Alert.java
- src/main/java/net/teumteum/alert/domain/AlertService.java
- src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
- src/main/resources/db/migration/V14__add_is_read_column_on_alert.sql
- src/test/resources/schema.sql
알람 조회에 읽은알람인지, 언제 발행되었는지를 추가했습니다.
- close #188
> refactor: 알람 조회에 읽은알람인지, 언제 발행되었는지를 추가

- src/main/java/net/teumteum/alert/app/AlertHandler.java
- src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
- 소셜 로그인 에러 긴급 수정
- token 없는 경우 체크 로직 추가
- close #214
> fix: 소셜 로그인 에러 긴급 수정 
