src/main/java/net/teumteum/meeting/domain/Meeting.java
src/main/java/net/teumteum/meeting/domain/MeetingArea.java
src/main/java/net/teumteum/meeting/domain/MeetingRepository.java
src/main/java/net/teumteum/meeting/domain/PromiseDateTime.java
src/main/java/net/teumteum/meeting/domain/Topic.java
src/main/resources/db/migration/V1__create_users.sql
src/main/resources/db/migration/V2__create_meeting.sql
src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
src/test/resources/application.properties
src/test/resources/schema.sql

Meeting 도메인과 Repository를 구현했습니다.
close #6 
- 모임 도메인 빠진 부분이 있는지 확인해주세요.
- 부족한 검증 로직이 존재하는지 확인해주세요.

feat: MeetingEntity와 MeetingRepository 개발

---

gradle/spring.gradle
src/main/java/net/teumteum/core/error/ErrorResponse.java
src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/ActivityArea.java
src/main/java/net/teumteum/user/domain/User.java
src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/user/domain/UserFixture.java
src/test/java/net/teumteum/user/integration/Api.java
src/test/java/net/teumteum/user/integration/IntegrationTest.java
src/test/java/net/teumteum/user/integration/Repository.java
src/test/java/net/teumteum/user/integration/UserIntegrationTest.java

유저 id로 유저 정보를 조회하는 API를 개발했습니다.
- close #11

feat: 유저 조회 API 개발

---

src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/response/FriendsResponse.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java

유저의 친구를 조회하는 API를 개발했습니다.
- close #26

feat: 유저의 친구 조회 API

---

src/main/java/net/teumteum/meeting/controller/MeetingController.java
src/main/java/net/teumteum/meeting/domain/Meeting.java
src/main/java/net/teumteum/meeting/service/MeetingService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java

feat: 유저가 참여한 모임을 취소한다.

---

gradle.properties
gradle/test.gradle
src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/InterestQuestion.java
src/main/java/net/teumteum/user/domain/response/InterestQuestionResponse.java
src/main/java/net/teumteum/user/infra/GptInterestQuestion.java
src/main/java/net/teumteum/user/infra/WebClientConfigurer.java
src/main/java/net/teumteum/user/service/UserService.java
src/main/resources/application-prod.yml
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/IntegrationTest.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/user/infra/GptInterestQuestionTest.java
src/test/java/net/teumteum/user/infra/GptTestServer.java
src/test/resources/application.properties

공통된 관심질문을 생성하는 기능을 개발했습니다.
(필요한 정보가 유저 정보밖에 없고 유저 도메인에 속하는기능 같아서, URL도 `/teum-teums/interests` -> `/users/interests` 로 변경했습니다.)
- close #28

feat: 공통 관심질문 생성 기능 개발

---

Dockerfile

Dockerfile의 jdk 버전을 21로 올렸습니다.
- close #57

build: Dockerfile jdk version 21로 업그레이드

---

src/main/resources/db/migration/V1__create_users.sql
src/test/resources/schema.sql

user 도메인의 authenticate 칼럼을 varchar(255)에서 enum으로 변경했습니다.
- close #69

fix: user 도메인 스키마가 맞지 않는 버그 수정

---

src/main/resources/db/migration/V4__update_users.sql
src/test/resources/schema.sql

user domain ddl 의 role_type을 enum으로 변경했습니다.
- close #72

fix: user domain role_type을 enum으로 변경

---

gradle/test.gradle
src/main/java/net/teumteum/core/security/service/SecurityService.java
src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/core/config/RedisTestContainerConfig.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/IntegrationTest.java
src/test/java/net/teumteum/integration/Repository.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java

- 회원 로그아웃 API 을 구현한다.
- close #52 
- https://github.com/depromeet/teum-teum-server/issues/52 브랜치는 로컬 https://github.com/depromeet/teum-teum-server/issues/73 에서 딴 브랜치라 https://github.com/depromeet/teum-teum-server/issues/73 커밋 기록이 포함되어 있습니다.
Redis 기능이 필수적인 API 라 부득이하게 https://github.com/depromeet/teum-teum-server/issues/73 에서 구현 시작했습니다.

feat: 회원 로그아웃을 구현한다.

---

src/main/java/net/teumteum/core/security/service/JwtService.java

운영 서버에서 발생하는 Jwt 파싱 에러를 해결합니다.
- close #86 
- [JWT 파싱 에러 해결](https://velog.io/@readnthink/SecretKey%ED%8C%8C%EC%8B%B1-%EC%98%A4%EB%A5%98-JWT-validity-cannot-be-asserted-and-should-not-be-trusted)

fix: 운영 서버 Jwt 파싱 에러 해결을 한다.

---

src/main/java/net/teumteum/user/infra/GptInterestQuestion.java

GPT 토큰이 `Bearer ...` 처럼 세팅되어있는 버그를 수정했습니다. 
- close #95

fix: GPT 토큰에 띄어쓰기가 들어가는 버그 수정

---

src/main/java/net/teumteum/meeting/controller/MeetingController.java
src/main/java/net/teumteum/meeting/domain/Meeting.java
src/main/java/net/teumteum/meeting/service/MeetingService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
src/test/java/net/teumteum/integration/Repository.java
src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java

모임 삭제 기능 구현
Close #76 
- 인텔리제이 포매터 고쳐서 수정 사항이 많아보이지만 별로 없습니다..
- 삭제 관련된 부분만 집중해서 봐주세오.. 🙏

feat: 모임 삭제 기능 구현

---

src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/User.java
src/main/java/net/teumteum/user/domain/request/UserRegisterRequest.java
src/main/java/net/teumteum/user/domain/request/UserUpdateRequest.java
src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java
src/main/java/net/teumteum/user/service/UserService.java
src/main/resources/db/migration/V5__update_users.sql
src/test/java/net/teumteum/integration/RequestFixture.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/unit/auth/common/SecurityValue.java
src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
src/test/java/net/teumteum/user/domain/UserFixture.java
src/test/resources/schema.sql

기존 `city` , `street` 을 하나의 객체로 받는 방식 -> `activityArea` 문자열 하나로 받는 방식으로 기획 변경, 기존 API 수정 및 요청,응답 객체 변경
- close #104

refactor: 기획 변경에 따른 회원 카드 등록 API 리팩토링

---

gradle.properties
gradle/devtool.gradle
src/main/java/net/teumteum/auth/service/AuthService.java
src/main/java/net/teumteum/auth/service/OAuthService.java
src/main/java/net/teumteum/core/security/filter/JwtAccessDeniedHandler.java
src/main/java/net/teumteum/core/security/filter/JwtAuthenticationEntryPoint.java
src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
src/main/java/net/teumteum/core/security/service/JwtService.java
src/test/java/net/teumteum/core/property/PropertyTest.java
src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
src/test/resources/application.properties

기존 JWT 로직을 변경했으며, 인증,인가 로직 예외 처리를 추가 구현했습니다.
- close #101

refactor: JWT 에러 응답 리팩토링 및 인가 인증 예최 처리 코드 수정

---

src/main/java/net/teumteum/user/domain/response/UserRegisterResponse.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
src/test/java/net/teumteum/user/domain/UserFixture.java
src/test/resources/application.properties

refactor: 회원 카드 등록시 JWT 정보도 함께 반환하도록 수정

---

src/main/java/net/teumteum/auth/controller/OAuthLoginController.java
src/main/java/net/teumteum/auth/domain/KakaoOAuthUserInfo.java
src/main/java/net/teumteum/auth/domain/OAuthToken.java
src/main/java/net/teumteum/auth/service/OAuthService.java
src/main/java/net/teumteum/core/security/SecurityConfig.java
src/main/resources/application-auth.yml
src/main/resources/application-datasource.yml

기존 OAuth 관련 에러를 수정했으며, 로직을 일부 개선했습니다.
- close #111 
📣 이거 오류 해결법 아시는분 까먹었습니다 찾아봐도 딱히..
📣 💯

fix: 소셜 로그인 관련 500 에러 수정 및 OAuth 로직 일부 개선

---

src/main/java/net/teumteum/meeting/controller/MeetingController.java
src/main/java/net/teumteum/meeting/service/MeetingService.java

모임 목록 조회 조건에 활동 지역 조건이 안걸리는 버그 수정
조건을 걸리도록 변경
#120

fix: 모임 목록 조회 조건에 활동 지역 조건이 안걸리는 버그 수정

---

src/main/java/net/teumteum/meeting/domain/MeetingArea.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
src/test/java/net/teumteum/meeting/domain/MeetingFixture.java

모임 거리명 저장 방식 변경
사용자 가입 시 저장하는 활동 지역과 모임 생성 시 사용하는 도로명 주소 API의 차이로 인한 수정
기존에 `강남구` 또는 `성남시` 처럼 저장되던 주소를 `서울 강남구` 또는 `경기 성남시` 형태로 변경
close #126

fix: 모임 규격 변경

---

src/main/java/net/teumteum/user/domain/response/UserGetResponse.java
src/main/java/net/teumteum/user/domain/response/UserMeGetResponse.java
src/main/java/net/teumteum/user/domain/response/UsersGetByIdResponse.java

유저조회, 자신조회, 유저들 조회 api의 응답에 친구 수 필드를 추가 했습니다.
- close #134

refactor: 유저조회, 자신조회, 유저들 조회 api응답에 친구 수 필드 추가

---

src/main/java/net/teumteum/core/config/RedisConfig.java
src/main/java/net/teumteum/core/security/service/RedisService.java
src/main/java/net/teumteum/teum_teum/controller/TeumTeumController.java
src/main/java/net/teumteum/teum_teum/domain/UserLocation.java
src/main/java/net/teumteum/teum_teum/domain/request/UserLocationRequest.java
src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
src/test/java/net/teumteum/integration/RedisRepository.java
src/test/java/net/teumteum/integration/Repository.java
src/test/java/net/teumteum/integration/TeumTeumIntegrationTest.java
src/test/java/net/teumteum/teum_teum/UserLocationFixture.java

우리 서비스의 기능 중 `친해지기` 기능을 위한 위치 기반 로직을 수정했습니다.
**(기존 Redis Geo 는 해당 기능을 구현하기에 적합하지 않다고 판단 ! Redis Geo 로 해결할 수 있을 것 같다면 피드백 부탁드립니다. )**
1. Redis Geo 는 유효기간 설정을 하지 못하는 이슈
2. 기본 Redis String 을 사용해서 직렬화 후 저장(조회하는 경우 역직렬화 필요)
3. 유효기간 설정 이유는 주변 유저 조회시 친해지기 앱을 통해 api 을 요청한지 1분이 지난 유저 데이터는 자연스럽게 거르기 위함힙니다.
- close #124 
- 🧭 위치기반 로직 
1. 현재 로그인한 유저는 위치기반 API 을 요청
2. 해당 유저 위치 업데이트 이때, 유효기간을 1분으로 설정(Redis 는 유효기간이 지나면 자동 삭제)
3. 그 후, 주변 100 m 이내 6명을 거리 순  역직렬화을 통해 오름차순으로 정렬해서 조회( 이때, 자기 id 와 동일한 데이터는 제외)
4. 이를 통해 redis 에서 모든 데이터를 조회해서 status 을 통해 거를 필요도 없고(유효기간 때문에), 또한 간단한 계산을 통해 6개만 뽑으면 되니 간단하게 로직을 구현할 수 있다.

refactor: 틈틈 위치 기반 로직 수정 및 테스트 

---

src/main/java/net/teumteum/core/security/service/SecurityService.java
src/test/java/net/teumteum/integration/IntegrationTest.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
src/test/java/net/teumteum/integration/SecurityContextSetting.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java

통합 테스트인 경우 `Thread Local` 로 동작해서 오류가 났던 인증 객체 적용 부분을 수정합니다.
- close #148 
`문제` :   기존 WebTestClient 로 통합 테스트를 진행하면 실제 테스트 대상 로직 (Controller) 에 진입하는 순간 SecurityContext 에 저장했던 인증 객체가 null 로 변하는 이슈가 있었습니다.
`원인` : SecurityContextHolder 가 Thread Local 로 동작하기 때문에 동일한 Test Context 에서도 유지되지 않았던 것 
`해결` : SecurityContextHolder 을 Global(전역) 으로 동작하도록 변경하였습니다.
- [Spring SecuritySecurityContextHolder 에 대해](https://hyunwook.dev/121)

refactor: 통합 테스트시 인증 객체 관련 로직 수정

---

src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/UserRepository.java
src/main/java/net/teumteum/user/domain/response/UserReviewsResponse.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
src/test/java/net/teumteum/user/domain/UserFixture.java
src/test/java/net/teumteum/user/domain/UserRepositoryTest.java

- 유저 리뷰 조회 기능을 개발
- close #147

feat: 유저 리뷰 조회 기능

---

src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/Review.java
src/main/java/net/teumteum/user/domain/User.java
src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/Repository.java
src/test/java/net/teumteum/integration/RequestFixture.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
src/test/java/net/teumteum/user/domain/UserFixture.java

- 회원의 신뢰도를 의미하는 매너 온도 반영 기능을 추가하며 리뷰 등록 기능을 리팩토링합니다.
- close #157

feat: 리뷰 등록시 회원 매너 온도 반영 기능 추가 및 리뷰 등록 리팩토링

---

src/main/java/net/teumteum/user/controller/UserController.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/meeting/domain/MeetingRepositoryTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java

- 기존 회원 탈퇴 URI 을 변경합니다.
- close #161

refactor: 회원 탈퇴 URI 변경

---

src/main/java/net/teumteum/alert/controller/AlertController.java
src/main/java/net/teumteum/alert/domain/AlertRepository.java
src/main/java/net/teumteum/alert/domain/AlertService.java
src/main/java/net/teumteum/alert/domain/UserAlert.java
src/main/java/net/teumteum/alert/domain/request/UpdateAlertTokenRequest.java
src/main/resources/db/migration/V10__create_alert.sql
src/test/java/net/teumteum/alert/domain/AlertRepositoryTest.java
src/test/resources/schema.sql

fcm token 업데이트 api 추가
- close #165

feat: fcm token 업데이트 api 추가

---

src/main/java/net/teumteum/core/security/service/RedisService.java
src/main/java/net/teumteum/teum_teum/domain/response/UserAroundLocationsResponse.java
src/main/java/net/teumteum/teum_teum/service/TeumTeumService.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java

- 기존 회원 탈퇴 및 로그아웃 시 위치 데이터가 남아있는 이슈가 있었고, 삭제 로직을 추가합니다.
- close #178

feat: 회원탈퇴, 로그아웃 시, 회원 위치 데이터 삭제 로직 추가 및 위치 데이터 유효기간 변경

---

src/main/java/net/teumteum/alert/app/AlertHandler.java
src/main/java/net/teumteum/meeting/controller/MeetingController.java
src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantsResponse.java
src/main/java/net/teumteum/meeting/service/MeetingService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java

모임 id 에 해당하는 모임 참여한 회원 정보 조회
- close #191

feat: 모임 참여자 정보 조회 기능을 구현

---

src/main/java/net/teumteum/alert/domain/AlertRepository.java
src/main/java/net/teumteum/alert/domain/AlertService.java
src/main/java/net/teumteum/alert/domain/response/AlertsResponse.java
src/main/java/net/teumteum/core/entity/TimeBaseEntity.java

Instant를 모두 LocalDateTime으로 변경했습니다.
Instant로 저장하고 클라한테 넘겨줄때 ZonedDateTime으로 주는게 좋긴한데, 나중에 세계로 나아갈때 변경하죠 
(지금은 시간 의존적인 동작이 있어서 KR타임으로 맞춤)
- close #199

refactor: Instant를 모두 LocalDateTime으로 변경

---

src/main/java/net/teumteum/core/security/filter/JwtAuthenticationFilter.java
src/test/java/net/teumteum/unit/auth/controller/AuthControllerTest.java
src/test/java/net/teumteum/unit/auth/service/AuthServiceTest.java
src/test/java/net/teumteum/unit/common/SecurityValue.java
src/test/java/net/teumteum/unit/core/security/JwtAuthenticationEntryPointTest.java
src/test/java/net/teumteum/unit/core/security/JwtAuthenticationFilterTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java

- JWT 관련 인증 단위 태스트을 구현하고 테스트 합니다.
- api 요청시 헤더를 통해 전달되는 JWT 인증 관련 단위 테스트
- api 요청시 Authentication Exception 발생시 호출되는 인증 실패 로직 관련 단위 테스트
- close #198

test: 인증 단위 테스트 구현

---

src/main/java/net/teumteum/meeting/controller/MeetingController.java
src/main/java/net/teumteum/meeting/domain/MeetingSpecification.java
src/main/java/net/teumteum/meeting/service/MeetingService.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java

로그인한 유저가 북마크한 모임 조회 기능 추가
#203 
- 테스트 코드 추후 추가하겠슴다 ㅎㅎ..

feat: 로그인한 유저가 북마크한 모임 조회

---

src/main/java/net/teumteum/user/controller/UserController.java
src/main/java/net/teumteum/user/domain/UserRepository.java
src/main/java/net/teumteum/user/domain/response/UserReviewResponse.java
src/main/java/net/teumteum/user/domain/response/UserReviewsResponse.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/Api.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java
src/test/java/net/teumteum/user/domain/UserRepositoryTest.java

- 현재 로그인한 회원의 리뷰 조회 로직에서 userId 에 해당하는 회원의 리뷰 조회 로직으로 변경
- close #217

feat: 기존 회원 리뷰 조회 API 로직 변경

---

src/main/java/net/teumteum/alert/app/AlertHandler.java
src/main/java/net/teumteum/alert/domain/UserAlertService.java
src/main/java/net/teumteum/user/domain/UserDeletedEvent.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java

- 유저가 삭제되었을때, 알람토큰도 삭제하도록 수정했습니다.
- close: #225

feat: 유저가 삭제되었을때, 알람토큰도 삭제하도록 수정

---

src/main/java/net/teumteum/meeting/service/MeetingAlertPublisher.java

모임 시작, 종료 알림을 모임 참여자가 3명 이상이 아니라면 발행되지 않도록 수정했습니다.
- close #230

fix: 모임 시작, 종료 알림이 모임 참여자가 3명 이상이 아니라면, 발행되지않도록 수정

---

src/main/java/net/teumteum/meeting/controller/MeetingController.java
src/main/java/net/teumteum/meeting/domain/response/MeetingParticipantResponse.java
src/main/java/net/teumteum/meeting/service/MeetingService.java
src/test/java/net/teumteum/integration/MeetingIntegrationTest.java
src/test/java/net/teumteum/integration/Repository.java
src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
src/test/java/net/teumteum/unit/meeting/controller/MeetingControllerTest.java
src/test/java/net/teumteum/unit/meeting/service/MeetingServiceTest.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java

- 모임 참여자 조회시, 로그인한 모임 참여자 응답 데이터는 제외하는 로직 및 포함 여부 확인 로직을 추가했습니다.
- close #228

feat: 리뷰 등록시 모임 참여 유저 조회 API 수정

---

src/main/java/net/teumteum/core/security/SecurityConfig.java
src/main/java/net/teumteum/user/domain/request/ReviewRegisterRequest.java
src/main/java/net/teumteum/user/service/UserService.java
src/test/java/net/teumteum/integration/Repository.java
src/test/java/net/teumteum/integration/UserIntegrationTest.java
src/test/java/net/teumteum/meeting/domain/MeetingFixture.java
src/test/java/net/teumteum/unit/user/controller/UserControllerTest.java
src/test/java/net/teumteum/unit/user/service/UserServiceTest.java

- 기존 리뷰 등록 관련 작업을 진행합니다.
- close #224

feat: 리뷰 등록시 요청 DTO Validation 변경 및 로직 추가
